### ISSUE TITLE
implement power switch for coffee machines

### ISSUE THREAD

**Issue by JohnBra** [smart-coffee/angular-pwa#1]

**Comment by blue995** [comment]
"/api/device/status GET" returns a json object with the property "device_runtime_state"
"device_runtime_state = 1" means, that the device is ON
"device_runtime_state = 2" means, that the device is OFF

To swtich the power state, you have to use the "/api/device/status PUT":
"device_runtime_state = 1" => turns device ON
"device_runtime_state = 2" => turns device OFF
